Adds docs for Kong testing
giantswarm/docs pull request #1328
Opened 2022-02-23 16:05 UTC by JosephSalisbury

Closes https://github.com/giantswarm/giantswarm/issues/20743

This PR adds a page for Kong documentation, particularly with documentation for how we test Kong (as requested by users).

### Please remember to

- [x] Give the PR a meaningful title -- it will be shown in the release notes
- [x] Add (or remove) [user questions](https://github.com/giantswarm/docs/blob/main/CONTRIBUTING.md#front-matter) associated with any updated docs

2022-02-24 15:58 UTC, marians requested changes
Two things:

- main headline is missing
- the title could be more straight forward

2022-02-25 16:25 UTC, JosephSalisbury commented
See https://github.com/giantswarm/giantswarm/issues/21076 for tracking adding enforcement of main headline existing to CI, we have articles that don't do that

2022-02-25 16:32 UTC, JosephSalisbury commented
@marians ptala, CI is still broken, but we can still review context while that gets fixed

2022-02-25 16:50 UTC, ubergesundheit commented
@JosephSalisbury you'll need to update to lastest master, this should fix CI

2022-02-25 17:41 UTC, JosephSalisbury commented
@ubergesundheit thanks! <3

2022-03-03 08:33 UTC, marians commented on src/content/app-platform/apps/kong/index.md
> +# Kong
You should remove the headline, as it will appear as part of the template, using `title` from the front matter.

2022-03-09 15:37 UTC, JosephSalisbury commented
this linting is going to make me lose my mind

2022-03-09 15:42 UTC, merged