Update sizing cluster article to ping external article
giantswarm/docs pull request #1889
Opened 2023-08-28 14:42 UTC by pipo02mix

After finding this good article on learnk8s we want to reference it in our docs

### What does this PR do?

(Please set a descriptive PR title. Use this space for additional explanations.)

Reviews the multi-tenancy cluster sizing article 

### What does it look like?

(If this is more than a textual change, a screenshot can help in some cases to speed up the review process.)

### Any background context you can provide?

(Please link public issues or summarize if not public.)

### What is needed from the reviewers?

### Have you maintained the front matter?

(Please bump the last_review_date in case this qualifies as a review for an entire page. Provide user_questions which should be answered in the page. Provide a meaningful description.)

2023-08-28 17:32 UTC, AndiDog requested changes

2023-08-28 17:32 UTC, AndiDog commented on src/content/getting-started/sizing-multi-tenancy/index.md
> +last_review_date: 2023-28-08
```suggestion
last_review_date: 2023-08-28
```

2023-08-28 17:32 UTC, AndiDog commented on src/content/getting-started/sizing-multi-tenancy/index.md
> +For production usage, the cluster should have at least 5 nodes and a buffer of 2 nodes. For further information on how to size your cluster please [read this learnk8s article](https://learnk8s.io/kub
```suggestion
For production usage, the cluster should have at least 5 nodes and a buffer of 2 nodes. For a deep dive on how to size your cluster, please [read this learnk8s.io article](https://learnk8s.io/kubernetes-node-size) which dives into all variables to consider when you don't know the type and number of nodes to configure for your cluster(s).
```

2023-08-28 17:32 UTC, AndiDog commented on src/content/getting-started/sizing-multi-tenancy/index.md
> + sensitive data, and/or one that holds services that need to fulfil certain compliance requirements.
```suggestion
 sensitive data, and/or one that holds services that need to fulfill certain compliance requirements.
```

(American English, which we mostly prefer)

2023-08-29 08:08 UTC, pipo02mix commented
@AndiDog I will wait for PR to fix linting before merging

2023-08-29 12:58 UTC, AndiDog approved these changes

2023-08-29 13:04 UTC, merged