Add new connectivity overview page
giantswarm/docs pull request #2186
Opened 2024-04-19 12:52 UTC by pipo02mix

### What this PR does / why we need it

Towards https://github.com/giantswarm/giantswarm/issues/30179

### Things to check/remember before submitting

- If you made content changes

    - Run `make dev` to render and proofread content changes locally.
    - Bump `last_review_date` in the front matter header if you reviewed the entire page.

2024-04-25 11:51 UTC, AndiDog reviewed
I'm not sure how to review this. I guess we should be more specific already in this draft, and therefore rather pull in Shield's docs champion to outline this overview draft?

2024-05-03 09:39 UTC, pipo02mix commented
It is a draft, I just marked it now. I have created a ticket to explain what is the purpose of this doc entry. I am hesitating if we need just an outline or we (as sig docs participants) can further facilitate the article's writing. Now the body contains the template outline and some suggestions on how to write it. My thinking was to let the champion write the draft and help him later with wording and syntax to be consistent and similar to other sibling pages. WDYT?

2024-05-03 09:47 UTC, pipo02mix commented on src/content/overview/connectivity/_index.md
> +Write a brief description of the the connectivity in general from introductory point of view.
```suggestion
The main idea is to write a brief description of connectivity and networking in general from an introductory point of view setting the high-level goals we would like to achieve.
```

2024-05-06 10:46 UTC, AndiDog commented
> It is a draft, I just marked it now. I have created a ticket to explain what is the purpose of this doc entry. I am hesitating if we need just an outline or we (as sig docs participants) can further facilitate the article's writing. Now the body contains the template outline and some suggestions on how to write it. My thinking was to let the champion write the draft and help him later with wording and syntax to be consistent and similar to other sibling pages. WDYT?

I think SIG Docs _could_ provide an outline, but then again the champion is the expert of what should even be included in the article (whether it's in "Overview" or "Getting started", doesn't matter). Getting together online to draft an outline could work, instead of trying that asynchronously (which might be slower).

2024-05-21 13:08 UTC, weatherhog requested changes
Maybe we should also add k8s-node-local-dns, external DNS and Kong? What do you think?

2024-05-21 13:08 UTC, weatherhog commented on src/content/overview/connectivity/_index.md
> +- **Traffic management**: manage traffic routing within your clusters using service mesh technologies like Linkerd, which provide advanced features like circuit breakers, retries, timeouts, and rate
I am not sure if we should keep it this way as we are not actively supporting service Mesh at the moment?

2024-05-21 13:08 UTC, weatherhog commented on src/content/overview/connectivity/_index.md
> +- **Linkerd**: As leading service mesh options, they enhance the security, reliability, and observability of microservices communication within your clusters.
same here I think we should remove Linkerd

2024-05-21 13:08 UTC, weatherhog commented on src/content/overview/connectivity/_index.md
> +- **Nginx**: Ingrees controller that helps in managing your ingress traffic efficiently, ensuring reliable routing of external traffic to your services.
Type here Ingrees instead of Ingress

2024-06-05 06:55 UTC, weatherhog approved these changes

2024-06-07 08:38 UTC, merged