Remove preinstalled apps from Changes and Releases
giantswarm/docs pull request #688
Opened 2020-12-03 20:28 UTC by marians

Towards https://github.com/giantswarm/giantswarm/issues/14712

2020-12-03 20:46 UTC, cokiengchiara commented on scripts/aggregate-changelogs/config.yaml
>    giantswarm/coredns-app:
this is a preinstalled app too

2020-12-03 20:47 UTC, cokiengchiara commented on scripts/aggregate-changelogs/config.yaml
>    giantswarm/net-exporter:
this is a preinstalled app too

2020-12-03 20:48 UTC, cokiengchiara requested changes
Thank you! Please remove coredns and net exporter too :)

2020-12-04 09:30 UTC, marians commented
@cokiengchiara Done

2020-12-04 12:45 UTC, cokiengchiara approved these changes
thanks so much! LGTM

2020-12-04 13:01 UTC, merged