Revisit nginx docs
giantswarm/docs pull request #787
Opened 2021-02-02 11:13 UTC by ubergesundheit

Towards giantswarm/giantswarm#15476

@cokiengchiara please take over. 

@giantswarm/team-halo could you verify if this stuff with the loadbalancers is correct? (not in the changes I've made)

2021-02-03 17:13 UTC, cokiengchiara commented
@ubergesundheit ,

I suggest we have two docs:
1. Running Multiple NGINX Controllers
2. Services of type LoadBalancer

And propose the following change:
- [ ] Change "Services of type LoadBalancer and Multiple Ingress Controllers" -> "Services of type LoadBalancer"
- [ ] Move all (still relevant) instructions on 'how to run multiple NGINX from "Services of type LoadBalancer" article to "Running Multiple NGINX Controllers" article

WDYT? This removes duplicate info. I tried to do the above, but I'm not knowledgeable enough to do it properly 😓  Can you do it? Or we could get on call if you want to work on it together

2021-02-04 10:06 UTC, ubergesundheit commented
> WDYT? This removes duplicate info. I tried to do the above, but I'm not knowledgeable enough to do it properly sweat Can you do it? Or we could get on call if you want to work on it together

Good Idea! I'll try to untangle them. Would be cool if you would check for sanity etc afterwards

2021-02-04 10:36 UTC, ubergesundheit commented
ping @cokiengchiara please check the latest changes

2021-02-05 10:39 UTC, marians commented
Heads-up: https://github.com/giantswarm/docs/pull/778 is going to be merged soon. The guide you are editing is moving to `/advanced/ingress/multi-nginx-ic/`

See https://docs-staging.c68pn.k8s.gollum.westeurope.azure.gigantic.io/advanced/ingress/multi-nginx-ic/ for a staging version.

2021-02-05 16:51 UTC, cokiengchiara commented on src/content/guides/multi-nginx/index.md
> +Further information on configuring NGINX Ingress Controller can be found in the [Services of type LoadBalancer]
```suggestion
Further information on configuring NGINX Ingress Controller can be found in the article, [Services of type LoadBalancer]({{< relref "/content/guides/services-of-type-loadbalancer/index.md" >}}).
```

2021-02-05 16:57 UTC, cokiengchiara commented on src/content/guides/multi-nginx/index.md
> +Further note that if you are running additional Ingress Controllers you might need to configure them so their Ingress Class does not collide with the class of our default NGINX Ingress Controller. Fo
We no longer have default (preinstalled) nginx in most clusters https://docs.giantswarm.io/general/releases/#apps - how does that change this?

Maybe sth like this?
```suggestion
Additionally, please ensure the Ingress Class of each of your Ingress Controllers do not collide with each other. For the community supported NGINX Ingress Controller this is described in the [official documentation](https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/).
```

2021-02-05 17:06 UTC, cokiengchiara commented
@ubergesundheit looking good. Thanks! One final suggestion on the order of things.

Would it make it clearer if
1. We added tl;dr at the top like below.
2. Rearrange sections like below.

---

tl;dr To install more than 1 NGINX Ingress Controller:
1. Install a second NGINX IC app (and subsequent apps) with a different NGINX global-only configuration. Ingress resources managed by this NGINX installation cannot be customized on a per-Ingress resource level.
2. Annotate each Ingress with the appropriate class. Make sure the Ingress Class of each Ingress Controller do not collide with each other

## Step 1: Install a second NGINX Ingress Controller

### Separating public from internal ingress traffic
### Using weak ciphers for legacy clients

## Step 2: Annotate each Ingress with the appropriate class

2021-02-08 14:27 UTC, ubergesundheit commented
@cokiengchiara wasn't sure how to apply your suggestion. please take a look

2021-02-09 16:46 UTC, cokiengchiara commented on src/content/advanced/ingress/multi-nginx-ic/index.md
> +Starting with [NGINX IC v1.8.0](https://github.com/giantswarm/nginx-ingress-controller-app/blob/master/CHANGELOG.md#180---2020-07-24), one can install multiple NGINX ingress controllers in a Kubernet
```suggestion
Starting with [NGINX IC v1.8.0](https://github.com/giantswarm/nginx-ingress-controller-app/blob/master/CHANGELOG.md#180---2020-07-24), one can install multiple NGINX ingress controllers in a Kubernetes cluster. The optional NGINX Ingress Controller can be [installed as as an App on your cluster]({{< relref "/content/getting-started/ingress-controller/index.md" >}}). This Ingress Controller is registered with the default `nginx` Ingress Class.
```
```suggestion
Starting with [NGINX IC v1.8.0](https://github.com/giantswarm/nginx-ingress-controller-app/blob/master/CHANGELOG.md#180---2020-07-24), one can install multiple NGINX ingress controllers in a Kubernetes cluster. The optional NGINX Ingress Controller can be [installed as an App on your cluster]({{< relref "/content/getting-started/ingress-controller/index.md" >}}). This Ingress Controller is registered with the default `nginx` Ingress Class.
```

2021-02-09 16:47 UTC, cokiengchiara commented on src/content/advanced/ingress/multi-nginx-ic/index.md
> +Starting with [NGINX IC v1.8.0](https://github.com/giantswarm/nginx-ingress-controller-app/blob/master/CHANGELOG.md#180---2020-07-24), one can install multiple NGINX ingress controllers in a Kubernet
```suggestion
Starting with [NGINX IC v1.8.0](https://github.com/giantswarm/nginx-ingress-controller-app/blob/master/CHANGELOG.md#180---2020-07-24), one can install multiple NGINX ingress controllers in a Kubernetes cluster. The optional NGINX Ingress Controller can be [installed as an App on your cluster]({{< relref "/content/getting-started/ingress-controller/index.md" >}}). This Ingress Controller is registered with the default `nginx` Ingress Class.
```

2021-02-09 16:52 UTC, cokiengchiara commented on src/content/advanced/ingress/service-type-loadbalancer/index.md
> +  - How do I configure an Ingress Controller with different functionality or performance?
```suggestion
```
Moving this to the multi nginx doc

2021-02-09 16:53 UTC, cokiengchiara commented on src/content/advanced/ingress/multi-nginx-ic/index.md
> +  - How do I configure NGINX Ingress Controller to allow weak ciphers for legacy devices?
```suggestion
  - How do I configure NGINX Ingress Controller to allow weak ciphers for legacy devices?
  - How do I configure an Ingress Controller with different functionality or performance?
```

2021-02-09 16:54 UTC, cokiengchiara requested changes
LGTM, thanks so much @ubergesundheit !

* Checked that the content is not duplicated in the two docs
* General clarity and flow
* User questions (thanks so much Gerald!)

I couldn't check for technical accuracy but I assume Gerald took care of that.

2021-02-09 16:55 UTC, cokiengchiara commented
> Heads-up: #778 is going to be merged soon. The guide you are editing is moving to `/advanced/ingress/multi-nginx-ic/`

@ubergesundheit LGTM. I made few more minor comments. Otherwise, feel free to merge. Also I don't know the implication of what Marian is saying, but I'm sure you do 😀

2021-02-09 19:09 UTC, ubergesundheit commented
@cokiengchiara giev approve plz

2021-02-10 09:15 UTC, cokiengchiara approved these changes

2021-02-10 09:32 UTC, merged